### ISSUE TITLE
Document is old?

### ISSUE THREAD

**Issue by bols-blue** [nerves-project/nerves_system_qemu_arm#17]
hello.

I try READMY.md.
But not working some mix tasks.
1) mix firmware.image task
Need additional arguments.
ex "mix firmware.image my_image.img"

2) mix nerves.gen.qemu_script task
I couldn't run this task.

Are there new documents?

**Comment by fhunleth** [comment]
It's too new. You're reading the instructions from the `master` branch. The `nerves.gen_qemu_script` command isn't in an official release yet, but it should be today. We have a planned release for this afternoon.
